Sokokapu_Stock_Management/Controllers/CategoriesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Sokokapu_Stock_Management.Data.Interfaces;
using Sokokapu_Stock_Management.Models;

namespace Sokokapu_Stock_Management.Controllers
{
    public class CategoriesController : Controller
    {
        private readonly IProductRepository _productRepository;
        private readonly ICategoryRepository _categoryRepository;

        public CategoriesController(IProductRepository productRepository, ICategoryRepository categoryRepository)
        {

            _productRepository = productRepository;
            _categoryRepository = categoryRepository;
        }




        [Authorize]
        public IActionResult ManageCategories()
        {


            var category = _categoryRepository.AllCategories();

            return View(category);

        }

        #region Create

        public IActionResult Create()
        {
            return View();
        }
        [HttpPost]
        public ActionResult Create(Category category)
        {

            if (ModelState.IsValid)
            {
                _categoryRepository.Add(category);
                return RedirectToAction(nameof(ManageCategories));
            }

            return View();
        }

        #endregion

        #region Edit
        //Get
        public ActionResult Edit(int id)
        {
            if (id <= 0)
            {
                return NotFound();
            }
            else
            {
                Category model = _categoryRepository.GetCategoryById(id);

                return View(model);

            }

        }

        //POST: Default/Edit/5
        [HttpPost]

        public ActionResult Edit(Category category)
        {

            if (ModelState.IsValid)
            {
                _categoryRepository.Edit(category);
            }

            return RedirectToAction("ManageCategories");
        }

        #endregion

        #region Deactivate
        //Get
        public ActionResult DeActivate(int id)
        {
            if (id <= 0)
            {
                return NotFound();
            }
            else
            {
                Category category = _categoryRepository.GetCategoryById(id);

                return View(category);

            }

        }

        //POST: Default/Edit/5
        [HttpPost]

        public ActionResult DeActivate(Category category)
        {

            if (ModelState.IsValid)
            {

                _categoryRepository.Edit(category);
            }

            return RedirectToAction("ManageCategories");
        }

        #endregion


    }
}

Sokokapu_Stock_Management/Controllers/ProductController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Sokokapu_Stock_Management.Data.Interfaces;
using Sokokapu_Stock_Management.Models;
using Sokokapu_Stock_Management.ViewModels;
using System;
using System.IO;
using System.Linq;

namespace Sokokapu_Stock_Management.Controllers
{
    public class ProductController : Controller
    {
        private readonly IHostingEnvironment _environment;
        private readonly IProductRepository _productRepository;
        private readonly ICategoryRepository _categoryRepository;

        public ProductController(IProductRepository productRepository, ICategoryRepository categoryRepository, IHostingEnvironment environment)
        {
            _environment = environment;
            _productRepository = productRepository;
            _categoryRepository = categoryRepository;
        }
        public IActionResult Index()
        {
            var products = _productRepository.AllProducts();

            var model = products.Select(p => new ProductViewModel()
            {
                Id = p.Id,
                ImageUrl = p.ImageUrl,
                ProductName = p.ProductName,
                Description = p.Description,
                Price = p.Price,
                Size = p.Size,
                InStock = p.InStock

            });


            return View(model);

        }

        #region Sold
        //TODO Just like editing
        public ActionResult Sold(int id)
        {
            if (id <= 0)
            {
                return NotFound();
            }
            else
            {
                Product model = _productRepository.GetProductById(id);

                EditProductVM edit = new EditProductVM
                {
                    Id = model.Id,
                    ProductName = model.ProductName,
                    Description = model.Description,
                    Price = model.Price,
                    Color = model.Color,
                    Quantity = model.Quantity,
                    NumberSold = model.NumberSold,
                    Size = model.Size,
                    ExistingImage = model.ImageUrl,
                    CategoryId = model.CategoryId,
                    _Category = model._Category,

                };

                ViewBag.CategoryId = new SelectList(_categoryRepository.AllCategories(), "Id", "Name", edit.CategoryId);
                return View(edit);

            }

        }

        //TODO
        //POST: Default/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Sold(EditProductVM model, int Sold)
        {
            if (ModelState.IsValid)
            {

                Product product = new Product
                {
                    Id = model.Id,
                    ProductName = model.ProductName,
                    Description = model.Description,
                    Price = model.Price,
                    Color = model.Color,
                    Quantity = model.Quantity,
                    Size = model.Size,
                    ImageUrl = model.ExistingImage,
                    CategoryId = model.CategoryId,
                    _Category = model._Category,
                    NumberSold = model.NumberSold + Sold
                };
                _productRepository.Edit(product);

            }

            return RedirectToAction("ManageProduct");
        }

        #endregion

        [Authorize]
        public IActionResult ManageProduct()
        {


            var products = _productRepository.AllProducts();

            return View(products);

        }

        #region Create

        public IActionResult Create()
        {

            ViewBag.CategoryId = new SelectList(_categoryRepository.AllCategories(), "Id", "Name");
            return View();


        }
        [HttpPost]
        public ActionResult Create(AddProductVM model)
        {

            if (ModelState.IsValid)
            {
                string uniqueFileName = FileCheck(model);
                model.NumberSold = 0;
                Product product = new Product
                {

                    ProductName = model.ProductName,
                    Description = model.Description,
                    Price = model.Price,
                    Color = model.Color,
                    Quantity = model.Quantity,
                    NumberSold = model.NumberSold,
                    Size = model.Size,
                    ImageUrl = uniqueFileName,
                    CategoryId = model.CategoryId,
                    _Category = model._Category

                };
                _productRepository.Add(product);
                return RedirectToAction(nameof(ManageProduct));


            }
            ViewBag.CategoryId = new SelectList(_categoryRepository.AllCategories(), "Id", "Name");

            return View();
        }

        #endregion

        #region Edit
        //Get
        public ActionResult Edit(int id)
        {
            if (id <= 0)
            {
                return NotFound();
            }
            else
            {
                Product model = _productRepository.GetProductById(id);

                EditProductVM edit = new EditProductVM
                {
                    Id = model.Id,
                    ProductName = model.ProductName,
                    Description = model.Description,
                    Price = model.Price,
                    Color = model.Color,
                    Quantity = model.Quantity,
                    NumberSold = model.NumberSold,
                    Size = model.Size,
                    ExistingImage = model.ImageUrl,
                    CategoryId = model.CategoryId,
                    _Category = model._Category,

                };

                ViewBag.CategoryId = new SelectList(_categoryRepository.AllCategories(), "Id", "Name", edit.CategoryId);
                return View(edit);

            }

        }

        //POST: Default/Edit/5
        [HttpPost]

        public ActionResult Edit(EditProductVM model)
        {

            if (ModelState.IsValid)
            {

                Product product = new Product
                {
                    Id = model.Id,
                    ProductName = model.ProductName,
                    Description = model.Description,
                    Price = model.Price,
                    Color = model.Color,
                    Quantity = model.Quantity,
                    NumberSold = model.NumberSold,
                    Size = model.Size
                };


                if (model.Photo != null)
                {
                    if (model.ExistingImage != null)
                    {
                        string filep = Path.Combine(_environment.WebRootPath, "images/", model.ExistingImage);
                        System.IO.File.Delete(filep);
                    }
                    product.ImageUrl = FileCheck(model);
                }
                else
                {
                    product.ImageUrl = model.ExistingImage;
                }

                product.CategoryId = model.CategoryId;
                product._Category = model._Category;

                _productRepository.Edit(product);


            }

            ViewBag.CategoryId = new SelectList(_categoryRepository.AllCategories(), "Id", "Name", model.CategoryId);

            return RedirectToAction("ManageProduct");
        }

        #endregion

        // GET: Products/Details/5
        public ActionResult Details(int id)
        {

            Product product = _productRepository.GetProductById(id);
            if (id <= 0)
            {
                return NotFound();
            }
            else
            {
                ProductViewModel model = new ProductViewModel()
                {

                    Id = product.Id,
                    ImageUrl = product.ImageUrl,
                    ProductName = product.ProductName,
                    Description = product.Description,
                    Price = product.Price,
                    Size = product.Size,
                    InStock = product.InStock
                };
                return View(model);
            }


        }

        #region Delete
        // GET: Products/Delete/5
        public ActionResult Delete(int id)
        {
            if (id <= 0)
            {
                return NotFound();
            }

            var product = _productRepository.GetProductById(id);



            if (product == null)
            {
                return NotFound();
            }

            return View(product);
        }

        // POST: Products/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            var p = _productRepository.GetProductById(id);
            if (p.ImageUrl != null)
            {
                string filep = Path.Combine(_environment.WebRootPath, "images/", p.ImageUrl);
                System.IO.File.Delete(filep);
            }

            _productRepository.Delete(id);

            return RedirectToAction(nameof(Index));
        }
        #endregion

        private string FileCheck(AddProductVM model)
        {
            string uniqueFileName = null;
            if (model.Photo != null)
            {
                string uploadsFolder = Path.Combine(_environment.WebRootPath, "images/");
                uniqueFileName = Guid.NewGuid().ToString() + "_" + model.Photo.FileName;
                string filePath = Path.Combine(uploadsFolder + uniqueFileName);
                using (var filestream = new FileStream(filePath, FileMode.Create))
                {
                    model.Photo.CopyTo(filestream);
                }


            }

            return uniqueFileName;
        }


    }

}

Sokokapu_Stock_Management/Views/Shared/AccountPartial.cshtml
@inject SignInManager<User> signInManager




@if (signInManager.IsSignedIn(User))
{
    <form asp-action="Logout" asp-controller="Account" method="post">
        <input style="background-color:#f06766;margin-top:15px" type="submit" name="name" value="Logout" />
    </form>

}
else
{
    <ul style="margin-top:15px">
        @*
            <li><a asp-action="Register" asp-controller="Account">Register</a></li>*@
        <li class="btn btn-success"><a asp-action="Login" asp-controller="Account">Login</a></li>
    </ul>
}

Sokokapu_Stock_Management/Views/Shared/_AccountLayout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Sokokapu_Stock_Management</title>

    <environment include="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
        <link href="~/css/site.css" rel="stylesheet" />
        <link href="~/css/site.css" rel="stylesheet" asp-append-version="true" />
        <script src="~/lib/jquery/jquery.min.js" asp-append-version="true"></script>
        <link href="~/lib/bootstrap/dist/css/bootstrap.min.css" rel="stylesheet" />
        <link href="~/lib/font-awesome/css/all.min.css" rel="stylesheet" />
    </environment>
    <environment exclude="Development">
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute" />
        <link rel="stylesheet" href="~/css/site.min.css" asp-append-version="true" />
    </environment>
</head>
<body>
    <div class="top-nav-div">
        <div class="top-nav-div-inner">
            <div class="div-logo">
                <a asp-action="Index" asp-controller="Product"> <h1><span class="span-green">Soko</span><span class="span-red">Kapu</span></h1></a>
                <div class="div-line"></div>
            </div>
        </div>

    </div>

    @*<partial name="_CookieConsentPartial" />*@


    <div class="container body-content">
        @RenderBody()

    </div>
    <footer>
        <p>&copy; 2019 - Sokokapu_Stock_Management</p>
    </footer>

    <environment include="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
        <script src="~/js/site.js" asp-append-version="true"></script>
    </environment>
    <environment exclude="Development">
        <script src="https://ajax.aspnetcdn.com/ajax/jquery/jquery-3.3.1.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery"
                crossorigin="anonymous"
                integrity="sha384-tsQFqpEReu7ZLhBV2VZlAu7zcOV+rXbYlF2cqB8txI/8aZajjp4Bqd+V6D5IgvKT">
        </script>
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                crossorigin="anonymous"
                integrity="sha384-aJ21OjlMXNL5UyIl/XNwTMqvzeRMZH2w8c5cRVpzpU8Y5bApTppSuUkhZXN0VxHd">
        </script>
        <script src="~/js/site.min.js" asp-append-version="true"></script>
    </environment>

    @RenderSection("Scripts", required: false)
</body>
</html>

Sokokapu_Stock_Management/Views/Shared/_Admin.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Sokokapu_Stock_Management</title>

    <environment include="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
        <link href="~/css/site.css" rel="stylesheet" />
        <link href="~/css/site.css" rel="stylesheet" asp-append-version="true" />
        <script src="~/lib/jquery/jquery.min.js" asp-append-version="true"></script>
        <link href="~/lib/bootstrap/dist/css/bootstrap.min.css" rel="stylesheet" />
        <link href="~/lib/font-awesome/css/all.min.css" rel="stylesheet" />
    </environment>
    <environment exclude="Development">
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute" />
        <link rel="stylesheet" href="~/css/site.min.css" asp-append-version="true" />
    </environment>
</head>
<body>
    <div class="top-nav-div-admin">
        <div class="top-nav-div-admin-inner">
            <a asp-action="Index" asp-controller="Product" class="div-logo">
                <h1><span class="span-green">Soko</span><span class="span-red">Kapu</span></h1>
                <div class="div-line"></div>
            </a>

        </div>

    </div>

    @*<partial name="_CookieConsentPartial" />*@
    <section class="main-section body-content">
        <aside>
            <div><a asp-action="ManageProduct" asp-controller="Product">Products</a></div>
            <div><a asp-action="ManageCategories" asp-controller="Categories">Categories</a></div>
            <div><a href="#">Users</a></div>
        </aside>
        <main>
            <div>
                @RenderBody()

            </div>
        </main>

    </section>
    <footer>
        <p>&copy; 2019 - Sokokapu_Stock_Management</p>
    </footer>

    <environment include="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
        <script src="~/js/site.js" asp-append-version="true"></script>
    </environment>
    <environment exclude="Development">
        <script src="https://ajax.aspnetcdn.com/ajax/jquery/jquery-3.3.1.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery"
                crossorigin="anonymous"
                integrity="sha384-tsQFqpEReu7ZLhBV2VZlAu7zcOV+rXbYlF2cqB8txI/8aZajjp4Bqd+V6D5IgvKT">
        </script>
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                crossorigin="anonymous"
                integrity="sha384-aJ21OjlMXNL5UyIl/XNwTMqvzeRMZH2w8c5cRVpzpU8Y5bApTppSuUkhZXN0VxHd">
        </script>
        <script src="~/js/site.min.js" asp-append-version="true"></script>
    </environment>

    @RenderSection("Scripts", required: false)
</body>
</html>

Sokokapu_Stock_Management/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Sokokapu_Stock_Management</title>

    <environment include="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
        <link href="~/css/site.css" rel="stylesheet" />
        <link href="~/css/site.css" rel="stylesheet" asp-append-version="true" />
        <script src="~/lib/jquery/jquery.min.js" asp-append-version="true"></script>
        <link href="~/lib/bootstrap/dist/css/bootstrap.min.css" rel="stylesheet" />
        <link href="~/lib/font-awesome/css/all.min.css" rel="stylesheet" />
    </environment>
    <environment exclude="Development">
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute" />
        <link rel="stylesheet" href="~/css/site.min.css" asp-append-version="true" />
    </environment>
</head>
<body>

    @inject SignInManager<User> signInManager
    <div class="top-nav-div">
        <div class="top-nav-div-inner">
            <div class="div-logo">
                <a asp-action="Index" asp-controller="Product"> <h1><span class="span-green">Soko</span><span class="span-red">Kapu</span></h1></a>
                <div class="div-line"></div>
            </div>
            @if (signInManager.IsSignedIn(User))
            {
                <div class="div-btn btn btn-success">
                    <a asp-action="ManageProduct" asp-controller="Product">Manage Products</a>
                </div>
            }

            <div>
                @await Html.PartialAsync("AccountPartial")
            </div>
        </div>

    </div>

    @*<partial name="_CookieConsentPartial" />*@


    <div class="container body-content">
        @RenderBody()

    </div>
    <footer>
        <p>&copy; 2019 - Sokokapu_Stock_Management</p>
    </footer>

    <environment include="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
        <script src="~/js/site.js" asp-append-version="true"></script>
    </environment>
    <environment exclude="Development">
        <script src="https://ajax.aspnetcdn.com/ajax/jquery/jquery-3.3.1.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery"
                crossorigin="anonymous"
                integrity="sha384-tsQFqpEReu7ZLhBV2VZlAu7zcOV+rXbYlF2cqB8txI/8aZajjp4Bqd+V6D5IgvKT">
        </script>
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                crossorigin="anonymous"
                integrity="sha384-aJ21OjlMXNL5UyIl/XNwTMqvzeRMZH2w8c5cRVpzpU8Y5bApTppSuUkhZXN0VxHd">
        </script>
        <script src="~/js/site.min.js" asp-append-version="true"></script>
    </environment>

    @RenderSection("Scripts", required: false)
</body>
</html>